.Dd $Mdocdate: Mar 1 2020$
.Dt ICS2TXT 1
.Os
.
.
.Sh NAME
.
.Nm ics2txt
.Nd convert ics file to simpler tsv or txt formats
.
.
.Sh SYNOPSIS
.
.Nm ics2txt-tsv Ar <file.ics >file.tsv
.Nm ics2txt-txt Ar <file.tsv >file.txt
.Nm ics2txt-ics Ar <file.tsv >file.ics
.Nm ics2txt-back Ar <file.txt >file.tsv
.
.Sh DESCRIPTION
.
.Nm
convert iCalendar 
.Pq ical
.Ar file.ics
or stdin if not specified to a tab separated value format, with one
line per entry, and one column per field:
.
.Bl -offset 1n -width 1n -enum -compact
.
.It
Begining (epoch)
.
.It
End (epoch)
.
.It
Category
.
.It
Location
.
.It
Summary
.
.It description
description
.
.El
.
.Pp
The
.Sq \en
and
.Sq \et
charaters may represent newlines and tabs.
.
.
.Sh SEE ALSO
.
.Xr cal 1 ,
.Xr calendar 1 ,
.Xr date 1
.
.
.Sh STANDARDS
.
.Rs
.%A Desruisseaux
.%D September 2009
.%T Internet Calendaring and Scheduling Core Object Specification (iCalendar)
.%R RFC 5545
.Re
.
.
.Sh AUTHORS
.
.An Josuah Demangeon Aq Mt me@josuah.net
