.Dd $Mdocdate: May 21 2018$
.Dt ICS2TXT 1
.Os
.
.
.Sh NAME
.
.Nm ics2txt
.Nd convert ics file to a simple plain text format
.
.
.Sh SYNOPSIS
.
.Nm Ar ics-file...
.
.
.Sh DESCRIPTION
.
.Nm
displays iCalendar 
.Pq ical, Pa .ics
.Ar file
or stdin if not specified in the format described by the command:
.
.
.Sh ENVIRONMENT
.
.Bl -tag -width 6n
.
.It Ev TZ
Timezone to use for printing the dates.
.
.El
.
.
.Sh SEE ALSO
.
.Xr cal 1 ,
.Xr calendar 1 ,
.Xr date 1
.
.Sh STANDARDS
.
.Rs
.%A Desruisseaux
.%D September 2009
.%T Internet Calendaring and Scheduling Core Object Specification (iCalendar)
.%R RFC 5545
.Re
.
.
.Sh AUTHORS
.
.An Josuah Demangeon Aq Mt mail@josuah.net
