.Dd $Mdocdate: March 05 2020$
.Dt TCAL 5
.Os
.
.
.Sh NAME
.
.Nm tcal
.Nd plaintext calendar event notation format
.
.
.Sh SYNOPSIS
.
TZ+0300
.
.
.Sh DESCRIPTION
.
The
.Nm
utility
.
.
.
.Sh FILES
.
.
.
.Sh EXAMPLES
.
.
.
.Sh SEE ALSO
.
.Xr foobar 1
.
.
.Sh STANDARDS
.
.
.
.Sh HISTORY
.
.
.
.Sh AUTHORS
.
.An <author-name>
.Aq Mt <author-email>
.
.
.Sh CAVEATS
.
.
.
.Sh BUGS
.
