.Dd $Mdocdate: Mar 1 2020$
.Dt TICAL 1
.Os
.
.
.Sh NAME
.
.Nm tical
.Nd convert ics file to simpler tsv or txt formats
.
.
.Sh SYNOPSIS
.
.Nm tical-tsv Ar <file.ics >file.tsv
.Nm tical-ics Ar <file.tsv >file.ics
.Nm tical-txt Ar <file.tsv >file.txt
.Nm tical-back Ar <file.txt >file.tsv
.
.Sh DESCRIPTION
.
.Nm
is set of awk scripts to deal with iCal
.Pq Pa .ics
format to publish, display and convert *.ics files, though a simple
central TSV format.
.Pp
They all read from either stdin or the file passed as argument, and
write to stdout.
.
.Pp
.The
.Pa file.tsv
files have one line per event, all with the following fields,
separated by one tab:
.
.Bl -offset 1n -width 1n -enum -compact
.
.It
Begining (epoch)
.
.It
End (epoch)
.
.It
Category
.
.It
Location
.
.It
Summary
.
.It
Description
.
.El
.
.
.Sh EXAMPLES
.
Convert a calendar from HTTP
.Pa .ics
to custom
.Pa .txt
sorted by beginning:
.Dl curl "$url.ics" | tical-tsv | sort -n -k 1,1 | tcal-txt
.
.Pp
Convert a custom
.Pa .txt
format back to an
.Pa .ics
file and publish it:
.Dl tical-back cal.txt | tcal-ics | ssh "www@$host" 'cat >/var/www/cal.ics'
.
.Pp
Split an
.ics
file according to the category, saved as
.Pa .tsv :
.Dl tical-tsv cal.txt | awk -F '\et' '{ f = $3".tsv"; print >>f }'
.
.
.Sh SEE ALSO
.
.Xr cal 1 ,
.Xr calendar 1 ,
.Xr date 1 ,
.Xr sort 1
.
.
.Sh STANDARDS
.
.Rs
.%A Desruisseaux
.%D September 2009
.%T Internet Calendaring and Scheduling Core Object Specification (iCalendar)
.%R RFC 5545
.Re
.
.
.Sh AUTHORS
.
.An Josuah Demangeon Aq Mt me@josuah.net
